---
- apiVersion: v1
  kind: Secret
  metadata:
    name: ocpreg
    namespace: $(APP_NAMESPACE)
  data:
    .dockerconfigjson: >-
      eyJhdXRocyI6eyJvY3ByZWcuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6Im9jcHJlZyIsInBhc3N3b3JkIjoiN3dtUXUxSTRmdEtKaDl3SnFBTDg9SmpiVWZNM0ZpTkciLCJhdXRoIjoiYjJOd2NtVm5PamQzYlZGMU1VazBablJMU21nNWQwcHhRVXc0UFVwcVlsVm1UVE5HYVU1SCJ9fX0=
  type: kubernetes.io/dockerconfigjson
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sso
  namespace: #{APP_NAMESPACE}#
spec:
  selector:
    matchLabels:
      application: sso
      deploymentConfig: sso
  template:
    metadata:
      name: sso
      labels:
        application: sso
        deploymentConfig: sso
        maistra.io/expose-route: 'true'
    spec:
      volumes:
        - name: sso-x509-https-volume
          secret:
            secretName: sso-x509-https-secret
            defaultMode: 420
        - name: sso-x509-jgroups-volume
          secret:
            secretName: sso-x509-jgroups-secret
            defaultMode: 420
        - name: service-ca
          configMap:
            name: sso-service-ca
            defaultMode: 420
      containers:
        - resources:
            limits:
              cpu: #{CPU_LIMIT}#
              memory: #{MEMORY_LIMIT}#
            requests:
              cpu: #{CPU_REQUEST}#
              memory: #{MEMORY_REQUEST}#
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/readinessProbe.sh
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: sso
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - /opt/eap/bin/livenessProbe.sh
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: SSO_HOSTNAME
            - name: DB_MIN_POOL_SIZE
            - name: DB_MAX_POOL_SIZE
            - name: DB_TX_ISOLATION
            - name: JGROUPS_PING_PROTOCOL
              value: openshift.DNS_PING
            - name: OPENSHIFT_DNS_PING_SERVICE_NAME
              value: sso-ping
            - name: OPENSHIFT_DNS_PING_SERVICE_PORT
              value: '8888'
            - name: X509_CA_BUNDLE
              value: >-
                /var/run/configmaps/service-ca/service-ca.crt
                /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - name: JGROUPS_CLUSTER_PASSWORD
              value: b42T3nfyeysuQNFtrpqfnEYJipgTTA5p
            - name: SSO_ADMIN_USERNAME
              value: pbadmin
            - name: SSO_ADMIN_PASSWORD
              value: DafCEd74PIvuYsYFvMUlqgfp3IiHmEKB
            - name: SSO_REALM
            - name: SSO_SERVICE_USERNAME
            - name: SSO_SERVICE_PASSWORD
          ports:
            - name: jolokia
              containerPort: 8778
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: ping
              containerPort: 8888
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: sso-x509-https-volume
              readOnly: true
              mountPath: /etc/x509/https
            - name: sso-x509-jgroups-volume
              readOnly: true
              mountPath: /etc/x509/jgroups
            - name: service-ca
              readOnly: true
              mountPath: /var/run/configmaps/service-ca
          terminationMessagePolicy: File
          image: 'ocpreg.azurecr.io/keycloak:#{Build.BuildNumber}#'
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
    imagePullSecrets:
      - name: ocpreg
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: "sso-x509-https-secret"
  name: sso
  namespace: #{APP_NAMESPACE}#
spec:
  ports:
  - port: 8443
    name: https
    protocol: TCP
    targetPort: 8443
  selector:
    application: sso
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The JGroups ping port for clustering.
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
    service.alpha.openshift.io/serving-cert-secret-name: sso-x509-jgroups-secret
  name: sso-ping
  namespace: #{APP_NAMESPACE}#
spec:
  ports:
  - port: 8888
    name: ping
    protocol: TCP
    targetPort: 8888
  selector:
    application: sso
  clusterIP: None
  clusterIPs:
    - None
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sso
  namespace: #{APP_NAMESPACE}#
spec:
  host: sso-#{APP_NAMESPACE}#.#{HOST_NAME}#
  tls:
    termination: reencrypt
  to:
    name: sso

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sso
  namespace: #{APP_NAMESPACE}#
spec:
  maxReplicas: #{MAX_HPA}#
  minReplicas: #{MIN_HPA}#
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sso
  targetCPUUtilizationPercentage: 75