pool:
  name: Azure Servers
  demands: sh

steps:
- task: DockerCompose@0
  displayName: 'Build Service'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: RedHAT
    action: 'Build services'
    additionalImageTags: '$(Build.BuildNumber)'
    dockerComposeCommand: '--no-cache'
    includeLatestTag: true

- task: DockerCompose@0
  displayName: 'Push Service'
  inputs:
    azureSubscription: 'AzurePRB_DEV'
    azureContainerRegistry: '{"loginServer":"keycloakbrq.azurecr.io", "id" : "/subscriptions/19d24e10-1ddf-4f7e-9615-abd8dc3b88d3/resourceGroups/Azure_ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/keycloakbrq"}'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'
    includeLatestTag: true
