pool:
  name: Azure Servers
  demands: sh

steps:
- task: DockerCompose@0
  displayName: 'Build Service'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: RedHAT
    action: 'Build services'
    additionalImageTags: '$(Build.BuildNumber)'
    dockerComposeCommand: '--no-cache'
    includeLatestTag: true

- task: DockerCompose@0
  displayName: 'Push Service'
  inputs:
    azureSubscription: 'AzurePRB_PROD'
    azureContainerRegistry: '{"loginServer":"ocpreg.azurecr.io", "id" : "/subscriptions/cc49fda0-bf9d-4180-a778-1b69960dfe68/resourceGroups/Azure_ContainerRegistry/providers/Microsoft.ContainerRegistry/registries/ocpreg"}'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'
    includeLatestTag: true
