apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: RHSSO
  description: Projeto Red Hat Single-Sign On e de customizacao de temas de login do PB. Utilizado para autenticação e autorização de clientes do Consignado e serviços de terceiro, alem de serviços internos
  tags:
    - rhsso76
    - bfb
  links:
    - url: https://sso-seguranca.apps.p.pbtech.net.br/auth/
      title: Aplicacao em Producao
      icon: code
      type: Repository
    - url: https://sso-seguranca-hom.apps.h.pbtech.net.br/auth/
      title: Aplicacao em Homologacao
      icon: code
      type: Repository
    - url: https://sso-seguranca-dev.apps.d.pbtech.net.br/auth/
      title: Aplicacao em Desenvolvimento
      icon: code
      type: Repository
    - url: http://vsm.homolog.jm:9999/tfs/Projetos/App-Seguranca/_git/RHSSO
      title: Repositorio
      icon: code
      type: Repository
  annotations:
    dev.azure.com/project-repo: App-Seguranca/RHSSO
    backstage.io/kubernetes-id: sso
    backstage.io/linguist: https://vsm.paranabanco.b.br/tfs/Projetos/App-Seguranca/_git/RHSSO
spec:
  type: service
  system: sso
  lifecycle: Production
  owner: coe-arquitetura-e-engenharia
  dependsOn:
    - resource:sqlserver
  providesApis:
    - PrbAuth